### ISSUE TITLE
Final tasks

### ISSUE THREAD

**Issue by Helaly96** [Helaly96/ImageProcessing-PongPing#1]
**1- Events with time stamps to show in the GUI
2- Comments and cleaning the main code
3- integrating the GUI with logic
4- integrating logic with stadium segmentation
5- ini file for the hard coded values**

**Comment by MHesham98** [comment]
Events with Timestamp Description:
Draw Trajectory
Draw Contour of the Ball
Display Score in GUI
Display Events(Hitting the Table, Hitting the net)

**Comment by Helaly96** [comment]
**1- Events with time stamps to show in the GUI
2- Comments and cleaning the main code ✔️
3- integrating the GUI with logic
4- integrating logic with stadium segmentation
5- ini file for the hard coded values✔️
6- Cleaning the stadium segmentation code ✔️**

**Comment by Helaly96** [comment]
1- Events with time stamps to show in the GUI
2- Comments and cleaning the main code ✔️
3- integrating the GUI with logic
4- integrating logic with stadium segmentation✔️
5- ini file for the hard coded values✔️
6- Cleaning the stadium segmentation code ✔️

**Comment by MHesham98** [comment]
1- Events with time stamps to show in the GUI
2- Comments and cleaning the main code ✔
3- integrating the GUI with logic ✔
4- integrating logic with stadium segmentation ✔
5- ini file for the hard coded values ✔
6- Cleaning the stadium segmentation code ✔

**Comment by Helaly96** [comment]
1- Events with time stamps to show in the GUI ✔
2- Comments and cleaning the main code ✔
3- integrating the GUI with logic ✔
4- integrating logic with stadium segmentation ✔
5- ini file for the hard coded values ✔
6- Cleaning the stadium segmentation code ✔
